
from abc import ABC, abstractmethod
from typing import Any, Dict, Set, Tuple, Optional
class World:
    def __init__(self, id: Any): self.id = id
    def __hash__(self): return hash(self.id)
    def __eq__(self, other): return isinstance(other, World) and self.id==other.id
class Model(ABC):
    @abstractmethod
    def worlds(self)->Set[World]: ...
    @abstractmethod
    def valuation(self, world: World, atom: str, args: Tuple[Any,...])->bool: ...
    @abstractmethod
    def accessibility(self, world: World, modality: str, agent: Optional[str]=None)->Set[World]: ...
    @abstractmethod
    def domain(self)->Set[Any]: ...
    @abstractmethod
    def interpret(self, term, assignment: Dict[str,Any])->Any: ...
    @abstractmethod
    def probability(self, world: World, event: Set[World])->float: ...
    @abstractmethod
    def preference(self, world: World, w1: World, w2: World)->bool: ...
